# This is a basic workflow to help you get started with Actions

name:  My-GitHub-Basics

on:
  push:
    branches: 
      - main
      
jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by"
