# This is a basic workflow to help you get started with Actions

name:  My-GitHub-Basics

# Controls when the workflow will run
on: 
  push:
    branches: 
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 my_test:
  runs-on: ubuntu-laster
  
  steps:
    - name: Print Hello_world
      run: echo "Hello_world"
